version: '3'
services:
    api:
        build: .
        ports: 
            - "5000:5000"
        # volumes:
        #     - ./uploads:/app/uoloads
    web:
        build: ./frontend
        ports: 
            - "80:80"